<!doctype html><html lang=cn><head><meta charset=utf-8><meta http-equiv=x-ua-compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><meta name=referrer content="no-referrer"><link rel=dns-prefetch href=https://i.geekbank.cf/><title>Node 脚本遭遇异常时如何安全退出 | 极客快訊</title><meta property="og:title" content="Node 脚本遭遇异常时如何安全退出 - 极客快訊"><meta property="og:type" content="article"><meta property="og:locale" content="cn"><meta property="og:image" content="https://p3.pstatp.com/large/dfic-imagehandler/a871ebab-ec2d-4b54-9bf4-035082ee6005"><link rel=alternate hreflang=x-default href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/b85602e.html><link rel=alternate hreflang=zh-tw href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/b85602e.html><link rel=alternate hreflang=zh-cn href=https://geekbank.cf/cn/%e7%a7%91%e6%8a%80/b85602e.html><link rel=alternate hreflang=zh-hk href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/b85602e.html><link rel=alternate hreflang=zh-mo href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/b85602e.html><link rel=alternate hreflang=zh-my href=https://geekbank.cf/cn/%e7%a7%91%e6%8a%80/b85602e.html><link rel=alternate hreflang=zh-sg href=https://geekbank.cf/cn/%e7%a7%91%e6%8a%80/b85602e.html><link rel=canonical href=https://geekbank.cf/tw/%e7%a7%91%e6%8a%80/b85602e.html><meta property="article:published_time" content="2020-10-29T21:04:55+08:00"><meta property="article:modified_time" content="2020-10-29T21:04:55+08:00"><meta name=Keywords content><meta name=description content="Node 脚本遭遇异常时如何安全退出"><meta name=author content="极客快訊"><meta property="og:url" content="/cn/%E7%A7%91%E6%8A%80/b85602e.html"><link rel=apple-touch-icon sizes=180x180 href=../../apple-touch-icon.png><link rel=icon type=image/png sizes=32x32 href=../../favicon-32x32.png><link rel=icon type=image/png sizes=16x16 href=../../favicon-16x16.png><link rel=manifest href=../../site.webmanifest><link rel=mask-icon href=../../safari-pinned-tab.svg color=#5bbad5><meta name=msapplication-TileColor content="#ffc40d"><meta name=theme-color content="#ffffff"><link rel=stylesheet href=https://geekbank.cf/css/normalize.css><link rel=stylesheet href=https://geekbank.cf/css/style.css><script type=text/javascript src=https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js></script><script type=text/javascript src=https://geekbank.cf/js/jqthumb.min.js></script><script data-ad-client=ca-pub-3525055026201463 async src=https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js></script></head><body><header id=header class=clearfix><div class=container><div class=col-group><div class=site-name><h1><a id=logo href>🤓 极客快讯 Geek Bank</a></h1><p class=description>为你带来最全的科技知识 🧡</p></div><div><nav id=nav-menu class=clearfix><a class=current href>猜你喜歡</a>
<a href=../../tw/categories/%E7%A7%91%E6%8A%80.html title=科技>科技</a>
<a href=../../tw/categories/%E9%81%8A%E6%88%B2.html title=遊戲>遊戲</a>
<a href=../../tw/categories/%E7%A7%91%E5%AD%B8.html title=科學>科學</a></nav></div></div></div></header><div id=body><div class=container><div class=col-group><div class=col-8 id=main><div class=res-cons><article class=post><header><h1 class=post-title>Node 脚本遭遇异常时如何安全退出</h1></header><date class="post-meta meta-date">2020-10-29</date><div class=post-meta><span>|</span>
<span class=meta-category><a href=cn/categories/%E7%A7%91%E6%8A%80.html>科技</a></span></div><div class=post-content><div class=pgc-img><img alt="Node 脚本遭遇异常时如何安全退出" onerror=errorimg.call(this); src=https://p3.pstatp.com/large/dfic-imagehandler/a871ebab-ec2d-4b54-9bf4-035082ee6005><p class=pgc-img-caption></p></div><p class=pgc-end-literature>作者：山月行</p><p class=pgc-end-literature>转发链接：https://mp.weixin.qq.com/s/LihozvtnAcVTN8s_v_ylFg</p><h1 class=pgc-h-arrow-right>前言</h1><p>一个 Node 相关的项目中，总是少不了跑脚本。跑一个脚本拉取配置、处理一些数据以及定时任务更是家常便饭。</p><p>在一些重要流程中能够看到脚本的身影：</p><ol start=1><li><span style="color:#595959;--tt-darkmode-color: #595959">CI，用于测试、质量保障及部署等</span></li><li><span style="color:#595959;--tt-darkmode-color: #595959">Docker，用以构建镜像</span></li><li><span style="color:#595959;--tt-darkmode-color: #595959">Cron，用于定时任务</span></li></ol><p>如果在这些重要流程中脚本出错无法及时发现问题，将有可能引发更加隐蔽的问题。</p><p>最近观察项目镜像构建，会偶尔发现一两个镜像虽然构建成功，但容器却跑不起来的情况。<strong><span style="color:#3594f7;--tt-darkmode-color: #3594F7">「究其原因，是因为 Exit Code 的问题」</span></strong>。</p><h1 class=pgc-h-arrow-right><strong><span style="color:#40b8fa;--tt-darkmode-color: #40B8FA">Exit Code</span></strong></h1><blockquote><p><span style="color:#595959;--tt-darkmode-color: #595959">❝</span></p><p><span style="color:#595959;--tt-darkmode-color: #595959">什么是 exit code?</span></p><p><span style="color:#595959;--tt-darkmode-color: #595959">❞</span></p></blockquote><p><span style="color:#3594f7;--tt-darkmode-color: #3594F7">exit code</span> 代表一个进程的返回码，通过系统调用 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">exit_group</span> 来触发。在 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">POSIX</span> 中，<span style="color:#3594f7;--tt-darkmode-color: #3594F7">0</span> 代表正常的返回码，<span style="color:#3594f7;--tt-darkmode-color: #3594F7">1-255</span> 代表异常返回码，一般主动抛出的错误码都是 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">1</span>。在 Node 应用中使用 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">process.exitCode = 1</span> 来代表因不期望的异常而中断。</p><p>这里有一张关于异常码的附表 <span style="color:#595959;--tt-darkmode-color: #595959">Appendix E. Exit Codes With Special Meanings[1]</span>。</p><p>异常码在操作系统中随处可见，以下是一个关于 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">cat</span> 命令的异常以及它的 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">exit code</span>，并使用 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">strace</span> 追踪系统调用。</p><pre><code>$ cat acat: a: No such file or directory# 使用 strace 查看 cat 的系统调用# -e 只显示 write 与 exit_group 的系统调用$ strace -e write,exit_group cat awrite(2, "cat: ", 5cat: )                    = 5write(2, "a", 1a)                        = 1write(2, ": No such file or directory", 27: No such file or directory) = 27write(2, "\n", 1)                       = 1exit_group(1)                           = ?+++ exited with 1 +++</code></pre><p>从系统调用的最后一行可以看出，该进行的 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">exit code</span> 是 1，并把错误信息输出到 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">stderr</span> (标准错误的 fd 为 2) 中</p><h1 class=pgc-h-arrow-right><strong><span style="color:#40b8fa;--tt-darkmode-color: #40B8FA">如何查看 exit code</span></strong></h1><p>从 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">strace</span> 中可以来判断进程的 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">exit code</span>，但是不够方便过于冗余，特别身处 shell 编程环境中。</p><p><strong><span style="color:#3594f7;--tt-darkmode-color: #3594F7">「有一种简单的方法，通过 echo $? 来确认返回码」</span></strong></p><pre><code>$ cat acat: a: No such file or directory$ echo $?1</code></pre><h1 class=pgc-h-arrow-right><strong><span style="color:#40b8fa;--tt-darkmode-color: #40B8FA">throw new Error与Promise.reject区别</span></strong></h1><p>以下是两段代码，第一段抛出一个异常，第二段 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">Promise.reject</span>，两段代码都会如下打印出一段异常信息，那么两者有什么区别？</p><pre><code>function error () {  throw new Error('hello, error')}error()// Output:// /Users/shanyue/Documents/note/demo.js:2//   throw new Error('hello, world')//   ^//// Error: hello, world//     at error (/Users/shanyue/Documents/note/demo.js:2:9)//     at Object.&lt;anonymous&gt; (/Users/shanyue/Documents/note/demo.js:5:1)//     at Module._compile (internal/modules/cjs/loader.js:701:30)</code></pre><pre><code>async function error () {  return new Error('hello, error')}error()// Output:// (node:60356) UnhandledPromiseRejectionWarning: Error: hello, world//    at error (/Users/shanyue/Documents/note/demo.js:2:9)//    at Object.&lt;anonymous&gt; (/Users/shanyue/Documents/note/demo.js:5:1)//    at Module._compile (internal/modules/cjs/loader.js:701:30)//    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)// (node:2787) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)// (node:2787) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.</code></pre><p>在对上述两个测试用例使用 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">echo $?</span> 查看 exit code，我们会发现<span style="color:#3594f7;--tt-darkmode-color: #3594F7">throw new Error()</span> 的 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">exit code</span> 为 1，而 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">Promise.reject()</span> 的为 0。</p><p><strong><span style="color:#3594f7;--tt-darkmode-color: #3594F7">「从操作系统的角度来讲，exit code 为 0 代表进程成功运行并退出，此时即使有 Promise.reject，操作系统也会视为它执行成功。」</span></strong></p><p>这在 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">Dockerfile</span> 与 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">CI</span> 中将留有安全隐患。</p><h1 class=pgc-h-arrow-right><strong><span style="color:#40b8fa;--tt-darkmode-color: #40B8FA">Dockerfile 在 node 中的注意点</span></strong></h1><p>当使用 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">Dockerfile</span> 构建镜像时，如果 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">RUN</span> 的进程返回非 0 的返回码，构建就会失败。</p><p><strong><span style="color:#3594f7;--tt-darkmode-color: #3594F7">「而在 Node 中的错误处理中，我们倾向于所有的异常都交由 async/await 来处理，而当发生异常时，由于此时 exit code 为 0 并不会导致镜像构建失败。」</span></strong></p><p>这是一个浅显易懂的含 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">Promise.reject()</span> 问题的镜像。</p><pre><code>FROM node:12-alpineRUN node -e "Promise.reject('hello, world')"</code></pre><p>构建镜像过程如下：<strong><span style="color:#3594f7;--tt-darkmode-color: #3594F7">「即使在构建过程打印出了 unhandledPromiseRejection 信息，但是镜像仍然构建成功。」</span></strong></p><pre><code>$ docker build -t demo .Sending build context to Docker daemon  33.28kBStep 1/2 : FROM node:12-alpine ---&gt; 18f4bc975732Step 2/2 : RUN node -e "Promise.reject('hello, world')" ---&gt; Running in 79a6d53c5aa6(node:1) UnhandledPromiseRejectionWarning: hello, world(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.Removing intermediate container 79a6d53c5aa6 ---&gt; 09f07eb993feSuccessfully built 09f07eb993feSuccessfully tagged demo:latest</code></pre><h1 class=pgc-h-arrow-right><strong><span style="color:#40b8fa;--tt-darkmode-color: #40B8FA">Promise.reject 脚本解决方案</span></strong></h1><p>能在编译时能发现的问题，绝不要放在运行时。所以，构建镜像或 CI 中需要执行 node 脚本时，对异常处理需要手动指定 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">process.exitCode = 1</span> 来提前暴露问题</p><pre><code>runScript().catch(() =&gt; {  process.exitCode = 1})</code></pre><p>在构建镜像时，也有关于异常解决方案的建议：</p><blockquote><p><span style="color:#595959;--tt-darkmode-color: #595959">❝</span></p><p><span style="color:#595959;--tt-darkmode-color: #595959">(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag </span><span style="color:#3594f7;--tt-darkmode-color: #3594F7">--unhandled-rejections=strict</span> (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)</p><p><span style="color:#595959;--tt-darkmode-color: #595959">❞</span></p></blockquote><p>根据提示，<span style="color:#3594f7;--tt-darkmode-color: #3594F7">--unhandled-rejections=strict</span> 将会把 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">Promise.reject</span> 的退出码设置为 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">1</span>，并在将来的 node 版本中修正 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">Promise</span>异常退出码。</p><pre><code>$ node --unhandled-rejections=strict error.js</code></pre><p><span style="color:#3594f7;--tt-darkmode-color: #3594F7">--unhandled-rejections=strict</span> 的配置对 node 有版本要求：</p><blockquote><p><span style="color:#595959;--tt-darkmode-color: #595959">❝</span></p><p><span style="color:#595959;--tt-darkmode-color: #595959">Added in: v12.0.0, v10.17.0</span></p><p><span style="color:#595959;--tt-darkmode-color: #595959">By default all unhandled rejections trigger a warning plus a deprecation warning for the very first unhandled rejection in case no unhandledRejection hook is used.</span></p><p><span style="color:#595959;--tt-darkmode-color: #595959">❞</span></p></blockquote><h1 class=pgc-h-arrow-right><strong><span style="color:#40b8fa;--tt-darkmode-color: #40B8FA">总结</span></strong></h1><ol start=1><li><span style="color:#595959;--tt-darkmode-color: #595959">当进程结束的 exit code 为非 0 时，系统会认为该进程执行失败</span></li><li><span style="color:#595959;--tt-darkmode-color: #595959">通过 </span><span style="color:#3594f7;--tt-darkmode-color: #3594F7">echo $?</span> 可查看终端上一进程的 exit code</li><li><span style="color:#595959;--tt-darkmode-color: #595959">Node 中 </span><span style="color:#3594f7;--tt-darkmode-color: #3594F7">Promise.reject</span> 时 exit code 为 0</li><li><span style="color:#595959;--tt-darkmode-color: #595959">Node 中可以通过 </span><span style="color:#3594f7;--tt-darkmode-color: #3594F7">process.exitCode = 1</span> 显式设置 exit code</li><li><span style="color:#595959;--tt-darkmode-color: #595959">在 Node12+ 中可以通过 </span><span style="color:#3594f7;--tt-darkmode-color: #3594F7">node --unhandled-rejections=strict error.js</span> 执行脚本，视 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">Promise.reject</span> 的 <span style="color:#3594f7;--tt-darkmode-color: #3594F7">exit code</span>为 1</li></ol><p class=pgc-end-literature>作者：山月行</p><p class=pgc-end-literature>转发链接：https://mp.weixin.qq.com/s/LihozvtnAcVTN8s_v_ylFg</p></div><div class="post-meta meta-tags"><ul class=clearfix><li><a>'Node','脚本','异常时'</a></li></ul></div></article></div></div><div id=secondary><section class=widget><form id=search action=//www.google.com/search method=get accept-charset=utf-8 target=_blank _lpchecked=1><input type=text name=q maxlength=20 placeholder=搜索>
<input type=hidden name=sitesearch value=geekbank.cf>
<button type=submit>🔍</button></form></section><section class=widget><h3 class=widget-title>最新文章 ⚡</h3><ul class=widget-list></ul></section><section class=widget><h3 class=widget-title>其他</h3><ul class=widget-list><li><a href=TOS.html>使用條款</a></li><li><a href=CommentPolicy.html>留言政策</a></li><li><a href=mailto:gdnews@tuta.io rel=nofollow>DMCA</a></li><li><a href=mailto:gdnews@tuta.io rel=nofollow>聯絡我們</a></li></ul></section></div></div></div></div><footer id=footer><div class=container>&copy; 2020 <a href>极客快訊</a></div></footer><script type=text/javascript>window.MathJax={tex2jax:{inlineMath:[['$','$']],processEscapes:true}};</script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML" async></script><a id=rocket href=#top></a><script type=text/javascript src=https://kknews.cf/js/totop.js async></script><script type=application/javascript>var doNotTrack=false;if(!doNotTrack){window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;ga('create','UA-146415161-2','auto');ga('send','pageview');}</script><script async src=https://www.google-analytics.com/analytics.js></script><script type=text/javascript src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5e508ed9e4e698bb"></script></body></html>